[project]
name = "maverik"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.6.2",
    "reflex>=0.5.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
